Supporting ARM64 (and still AMD64) architectures. Traefik binaries adjusted. Swapped miniforge in for miniconda.
jupyterhub/the-littlest-jupyterhub pull request #679
Opened 2021-04-04 22:02 UTC by cdibble

- [X ] Add / update documentation
 -  This PR shouldn't change anything from the user's point of view, but I added a couple of lines to state explicitly that this supports ARM 64 and AMD64 architectures and that it uses a miniforge conda environment.
 - [ X] Add tests
 - Updated ``tests/test_conda.py`` to use the miniforge installer instead of miniconda.

2021-09-22 15:46 UTC, meeseeksmachine commented
This pull request has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/tljh-on-m1-mac-arm-docker-installer-is-x86-specific/10894/2

2021-10-31 10:55 UTC, consideRatio requested changes
@cdibble are you okay with me cleaning up the git history of this PR a bit and applying the changes suggested in my comments?

2021-10-31 10:55 UTC, consideRatio commented on tljh/utils.py
> +
```suggestion

```

2021-10-31 10:55 UTC, consideRatio commented on tljh/traefik.py
> +    """Download and install the traefik binary-- prefix = '/opt/tljh/hub/'"""
```suggestion
    """Download and install the traefik binary to a location identified by a prefix path such as '/opt/tljh/hub/'"""
```

2021-10-31 10:55 UTC, consideRatio commented on tljh/traefik.py
> +# traefik_version = "1.7.18"
```suggestion
```

2021-10-31 10:55 UTC, consideRatio commented on tljh/installer.py
> +            logging.info(installer_path)
```suggestion
```

2021-10-31 10:55 UTC, consideRatio commented on tljh/conda.py
> +           raise Exception('sha256sum hash mismatch! Downloaded file corrupted')
```suggestion
            raise Exception('sha256sum hash mismatch! Downloaded file corrupted')
```

2021-10-31 10:55 UTC, consideRatio commented on tests/test_conda.py
```suggestion


```

2021-10-31 10:55 UTC, consideRatio commented on tests/test_conda.py
> +
```suggestion
```

2021-10-31 10:55 UTC, consideRatio commented on setup.py
> +    url='https://github.com/cdibble/the-littlest-jupyterhub',
```suggestion
    url='https://github.com/jupyterhub/the-littlest-jupyterhub',
```

2021-10-31 10:55 UTC, consideRatio commented on docs/topic/installer-actions.rst
> +By default, a ``miniforge`` conda environment is installed in ``/opt/tljh/user``. This contains
```suggestion
By default, a ``mambaforge`` conda environment is installed in ``/opt/tljh/user``. This contains
```

2021-10-31 10:55 UTC, consideRatio commented on docs/index.rst
>  **Ubuntu 18.04**. Earlier versions of Ubuntu are not supported.
```suggestion
The Littlest JupyterHub (TLJH) can run on any server that is running **Ubuntu 18.04** or **Ubuntu 20.04** on a amd64 or arm64 CPU architecture. Earlier versions of Ubuntu are not supported.
```

2021-10-31 10:55 UTC, consideRatio commented on bootstrap/bootstrap.py
> +    )
```suggestion
```

2021-10-31 10:55 UTC, consideRatio commented on .circleci/config.yml
> +version: 2.1
```suggestion
# We use circleci to test our support for the Arm64 architecture. This file should mimic
# what is done in the GitHub workflows.
#
version: 2.1
```

2021-11-01 20:09 UTC, cdibble commented
Hey @consideRatio - yes thank you for picking up the slack. I did bumble the git history badly didn't I. My apologies- a result of having rolled back a bunch of the changes in this original PR and then add some new changes from there. My own attempt to squash was ugly and I was too distracted with work projects to re-do it last week. So my apologies for that and thank you for making those changes.

Would you like me to go ahead and commit those suggestions to the PR?

2021-11-03 21:54 UTC, consideRatio commented
@cdibble I've squashed this PR into a few commits now, does this look okay to you?

I refactored some indentation etc as well in circleci config. I have a backup available of the previous PR state, and you probably have it as well on your local computer.

2021-11-03 21:58 UTC, cdibble commented
> @cdibble I've squashed this PR into a few commits now, does this look okay to you?
> 
> I refactored some indentation etc as well in circleci config. I have a backup available of the previous PR state, and you probably have it as well on your local computer.

LGTM. Thanks for doing that @consideRatio. You could drop that commit [08d937b](https://github.com/jupyterhub/the-littlest-jupyterhub/pull/679/commits/08d937b9902d7d947e9426fe04cf1366edbeefaa) and go back to the TLJH default of `tries=20` -- I had only bumped that up to help out with some dev and I didn't really mean for it to sneak into the PR. Of course, it doesn't really hurt anything, but in most cases where things actually work, `tries=20` is plenty.

2021-11-03 22:08 UTC, consideRatio commented
> but in most cases where things actually work, tries=20 is plenty.

Ah I wondered about that! Okay thanks for clarifying this @cdibble, and thanks for your work with this PR, thanks for sticking with it even though we were very low on maintenance capacity for a while in this repo! :heart: :tada:

2021-11-03 22:08 UTC, consideRatio approved these changes

2021-11-03 22:11 UTC, cdibble commented
Awesome @consideRatio - I am glad to be of some help and I much appreciate this project and all of its contributors!

My apologies for the added overhead here- my own need to refresh my knowledge of what was going on led to some fumbling.

2021-11-03 22:47 UTC, merged

2021-11-03 22:47 UTC, consideRatio commented
Wieee! Thanks again @cdibble!!!! :heart: :tada: